import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const wooridaum = localFont({
    src: [
        {
            path: './assets/fonts/WooridaumL.ttf',
            weight: '300',
            style: 'normal',
        },
        {
            path: './assets/fonts/WooridaumR.ttf',
            weight: '400',
            style: 'normal',
        },
        {
            path: './assets/fonts/WooridaumB.ttf',
            weight: '700',
            style: 'normal',
        },
    ],
    display: 'swap',
    variable: '--font-wooridaum',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' className={`${wooridaum.variable}`}>
            <body>{children}</body>
        </html>
    );
}
