server:
  port: 8080

ai:
  server:
    url: http://127.0.0.1:8000

spring:
  profiles:
    active: local


  data:
    mongodb:
      uri: mongodb://localhost:27017/woori_card

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, threaddump
